version: '3'

services:
  server:
    image: beuzus/commento-front
    build: .
    ports:
      - 8080:8080
    environment:
      WEBHOOK: https://server.elfeed.net/commentoWebhook
      COMMENTO_ORIGIN: http://commentoyo.elfeed.net
      COMMENTO_PORT: 8080
      COMMENTO_POSTGRES: postgres://beuzudo:3gG9b4skkk@db:5432/commento?sslmode=disable
    depends_on:
      - db
    networks:
      - db_network
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: beuzudo
      POSTGRES_PASSWORD: 3gG9b4skkk
    networks:
      - db_network
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

networks:
  db_network:

volumes:
  postgres_data_volume:

